# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
classes:
  - wso2am_runtime

wso2::template_list:
  - repository/conf/datasources/am-datasources.xml
  - repository/conf/api-manager.xml
  - repository/conf/identity/identity.xml
  - repository/conf/identity/application-authentication.xml
  - repository/conf/identity/EndpointConfig.properties
#  - bin/ciphertool.sh

# File list to be copied to the product folder, if there are changes found in the files, the system
# service will be restarted
#wso2::file_list:
#  - "repository/resources/security/%{hiera('wso2::trust_store')}"
#  - repository/conf/security/cipher-tool.properties
#  - repository/conf/security/cipher-text.properties
#  - repository/conf/security/secret-conf.properties


# Files to be copied to the product folder when restarting the system service
#wso2::service_refresh_file_list:
#  - password-tmp

#wso2::ports:
#  proxyPort:
#    http: 80
#    https: 443

wso2::service_name: wso2am
wso2::hostname: am.dev.wso2.org
wso2::mgt_hostname: am.dev.wso2.org
wso2::product_profile: default
wso2::pack_filename: wso2am-2.1.0.zip

wso2::apim_traffic_manager:
  host: am.dev.wso2.org
  port: 9443
  receiver_url_port: 9611
  auth_url_port: 9711
  jms_url_port: 5672
  username: "%{hiera('wso2::super_admin::username')}"
  password: "%{hiera('wso2::super_admin::password')}"

wso2::environments:
  apim_gateway_env1:
    host: am.dev.wso2.org
    port: 9443
    api_endpoint_host: am.dev.wso2.org
    api_endpoint_port: 8280
    secure_api_endpoint_port: 8243
    api_token_revoke_endpoint_port: 8280
    secure_api_token_revoke_endpoint_port: 8243
    username: "%{hiera('wso2::super_admin::username')}"
    password: "%{hiera('wso2::super_admin::password')}"

wso2::apim_keymanager:
  host: am.dev.wso2.org
  port: 9443
  username: "%{hiera('wso2::super_admin::username')}"
  password: "%{hiera('wso2::super_admin::password')}"

wso2::apim_store:
  host: am.dev.wso2.org
  port: 9443

wso2::apim_publisher:
  host: am.dev.wso2.org
  port: 9443

wso2::hosts_mapping:
  api_manager:
    ip: 127.0.0.1
    name: am.dev.wso2.org

# Use H2 based wso2_am_db in a stand-alone setup. In a clustered setup this should point to a MySQL data source
wso2::is_datasource: wso2_am_db
wso2::am_datasource: wso2_am_db
wso2::mb_store_datasource: wso2_mb_store_db
wso2::analytics: {}

## Uncomment the following key_store and trust_store to include the certificate of keymanager in gateway in a clustered setup
#wso2::key_store: wso2carbon.jks
#wso2::trust_store: client-truststore.jks

wso2::am_datasources:
  wso2_am_db:
    name: WSO2_AM_DB
    description: The datasource used for API Manager database
    driver_class_name: "%{hiera('wso2::datasources::h2::driver_class_name')}"
    url: jdbc:h2:repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE
    username: "%{hiera('wso2::datasources::common::username')}"
    password: "%{hiera('wso2::datasources::common::password')}"
    jndi_config: jdbc/WSO2AM_DB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::h2::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::master_datasources:
  wso2_mb_store_db:
    name: WSO2_MB_STORE_DB
    description: The datasource used for message broker database
    driver_class_name: "%{hiera('wso2::datasources::h2::driver_class_name')}"
    url: jdbc:h2:repository/database/WSO2MB_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    username: "%{hiera('wso2::datasources::common::username')}"
    password: "%{hiera('wso2::datasources::common::password')}"
    jndi_config: WSO2MBStoreDB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::h2::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

  wso2_am_stats_db:
    name: WSO2AM_STATS_DB
    description: The datasource used for getting statistics to API Manager
    driver_class_name: "%{hiera('wso2::datasources::h2::driver_class_name')}"
    url: jdbc:h2:../tmpStatDB/WSO2AM_STATS_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000;AUTO_SERVER=TRUE
    username: "%{hiera('wso2::datasources::common::username')}"
    password: "%{hiera('wso2::datasources::common::password')}"
    jndi_config: jdbc/WSO2AM_STATS_DB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::h2::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::enable_advance_throttling: true
wso2::enable_thrift_server: true
wso2::thrift_server_host: localhost
wso2::key_validator_client_type: ThriftClient
wso2::enable_data_publisher: true
wso2::enable_block_condition: true
wso2::enable_jms_connection_details: true
wso2::disable_jms_event_parameters: false
wso2::apply_publisher_specific_configurations: false
wso2::apply_store_specific_configurations: false
wso2::apply_gateway_specific_configurations: false
wso2::enable_log_analyzer: false
wso2::key_store: wso2carbon.jks
wso2::trust_store: client-truststore.jks
# Secure vault configuration
#wso2::enable_secure_vault: true
