# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
classes:
  - wso2am_analytics
#If you are using MySQL 5.7 for external  is used, the value of following parameter should be changed to VARCHAR(100)
wso2::type_mapping_string_type_mysql: VARCHAR(254)


wso2::service_name: wso2am_analytics
wso2::hostname: analytics.dev.wso2.org
wso2::mgt_hostname: analytics.dev.wso2.org
wso2::pack_filename: wso2am-analytics-2.1.0.zip

wso2::key_store: wso2carbon.jks
wso2::trust_store: client-truststore.jks

# File list to be copied to the product folder, if there are changes found in the files, the system
# service will be restarted
wso2::file_list:
#  - "repository/components/lib/%{hiera('wso2::datasources::mysql::connector_jar')}"
  - "repository/resources/security/%{hiera('wso2::key_store')}"
  - "repository/resources/security/%{hiera('wso2::trust_store')}"
#  - repository/conf/security/cipher-tool.properties
#  - repository/conf/security/cipher-text.properties
#  - repository/conf/security/secret-conf.properties


# Files to be copied to the product folder when restarting the system service
#wso2::service_refresh_file_list:
#  - password-tmp

wso2::datasources::mysql::connector_jar: mysql-connector-java-5.1.39-bin.jar

wso2::ports:
  offset: 1

wso2::portal:
  hostname: analytics.dev.wso2.org

wso2::template_list:
  - repository/conf/datasources/analytics-datasources.xml
  - repository/conf/analytics/spark/spark-jdbc-config.xml
  - repository/conf/datasources/stats-datasources.xml
#  - bin/ciphertool.sh

wso2::directory_list:
  - dbscripts/identity

wso2::spark:
  master: local
  master_count: 1
  hostname: "%{::ipaddress}"

wso2::single_node_deployment:
  enabled: true

wso2::is_datasource: wso2_carbon_db

wso2::analytics_datasources:
  wso2_analytics_event_store_db:
    name: WSO2_ANALYTICS_EVENT_STORE_DB
    description: The datasource used for analytics record store
    driver_class_name: "%{hiera('wso2::datasources::mysql::driver_class_name')}"
    url: jdbc:mysql://192.168.57.210:3306/analyticseventstoredb?autoReconnect=true
    username: "%{hiera('wso2::datasources::mysql::username')}"
    password: "%{hiera('wso2::datasources::mysql::password')}"
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

  wso2_analytics_processed_data_store_db:
    name: WSO2_ANALYTICS_PROCESSED_DATA_STORE_DB
    description: The datasource used for analytics record store
    driver_class_name: "%{hiera('wso2::datasources::mysql::driver_class_name')}"
    url: jdbc:mysql://192.168.57.210:3306/analyticprocesseddatastoredb?autoReconnect=true
    username: "%{hiera('wso2::datasources::mysql::username')}"
    password: "%{hiera('wso2::datasources::mysql::password')}"
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::stats_datasources:
  wso2_am_stats_db:
    name: WSO2AM_STATS_DB
    jndi_config: jdbc/WSO2AM_STATS_DB
    description: The datasource used for setting statistics to API Manager
    driver_class_name: "%{hiera('wso2::datasources::mysql::driver_class_name')}"
    url: jdbc:mysql://192.168.57.210:3306/statdb?autoReconnect=true
    username: "%{hiera('wso2::datasources::mysql::username')}"
    password: "%{hiera('wso2::datasources::mysql::password')}"
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

#wso2::clustering:
#  enabled: false
#  domain: das.wso2.domain
#  local_member_host: "%{::ipaddress}"
#  local_member_port: 4000
#  sub_domain: mgt
## WKA membership scheme
#  membership_scheme: wka
#  wka:
#    members:
#      -
#        hostname: 192.168.100.61
#        port: 4000
#      -
#        hostname: 192.168.100.62
#        port: 4000

# Secure vault configuration
#wso2::enable_secure_vault: true